### PR TITLE
Update if-else.ipynb

### PR DESCRIPTION
**Pull request by SomnathSengupta**
I have added one comment line

### CODE REVIEW

**Review by Alik-Agarwala — COMMENTED** [review]
Changes required!
We're working on

**Review by AvikAgarwala — APPROVED** [review]

**Comment by SomnathSengupta** [comment]
Thank You for merging .

**Comment by AvikAgarwala** [comment]
@SomnathSengupta add comments carefully. Don't make the notebook broken,

**Comment by SomnathSengupta** [comment]
Sorry sorry.... from next time it will not happen.

**Pull request merged**
